### ISSUE TITLE
Range error when click on genetics path

### ISSUE THREAD

**Issue by malvidah** [kaspnilsson/curyte-issues#2]
**Describe the bug**
Click on genetics path and it throws a range error.

**Expected:**
Click on path to go to path

**Unexpected Result:**
RangeError: Invalid "number" argument: NaN
    at C (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:129022)
    at A (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:129187)
    at e.value (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:126714)
    at e.value (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:145223)
    at e.value (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:144398)
    at https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:199881
    at Object.useMemo (https://www.curyte.com/_next/static/chunks/framework-91d7f78b5b4003c8.js:1:65395)
    at t.useMemo (https://www.curyte.com/_next/static/chunks/framework-91d7f78b5b4003c8.js:1:125458)
    at I (https://www.curyte.com/_next/static/chunks/639-5e241336282b1455.js:1:200063)
    at ro (https://www.curyte.com/_next/static/chunks/framework-91d7f78b5b4003c8.js:1:59430)

**To Reproduce**
1. Go to 'workspace'
2. Click on 'genetics path'

 OS: MacOS
 Browser: Chrome

**Comment by kaspnilsson** [comment]
I can't see or search your paths, can you link the broken path / lesson from now on when there's a reproducible issue with a specific one?

**Comment by malvidah** [comment]
yeah makes sense. do you still need it or were you able to address this? 

https://www.curyte.com/paths/edit/3__4jBYS-B-SIl5P

it's pulling up no problem now but didn't see a pull request. guess you already merged fixes over?

**Comment by kaspnilsson** [comment]
Hmm, no, didn't do anything
