### ISSUE TITLE
NotFoundError on insert before

### ISSUE THREAD

**Issue by malvidah** [kaspnilsson/curyte-issues#5]
Replicate:
Editing a lesson
copy pasted text from a collapsible into another collapsible element.

Mac OSX and chrome

Something went wrong :/
NotFoundError
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at _u (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:89431)
    at _u (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:89504)
    at _u (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:89504)
    at _u (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:89504)
    at _u (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:89504)
    at Su (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:88929)
    at Ri (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:101721)
    at t.unstable_runWithPriority (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:129336)
    at Ql (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:44981)
    at Oi (https://www.curyte.com/_next/static/chunks/framework-5f4595e5518b5600.js:1:99849)

**Comment by kaspnilsson** [comment]
Not able to reproduce. Loom?

**Comment by kaspnilsson** [comment]
@mindnmattr
